balena-os/balena-engine

api/server/router/build/build_routes.go
api/types/client.go
builder/dockerfile/internals.go
client/image_build.go
vendor.conf
vendor/github.com/docker/cli/cli/command/image/build.go

This can be used to implement various caching schemes that are finer grained than layer invalidation.
Resolves issue moby/moby#14080

Build time volumes

---

distribution/xfer/download_test.go

Added a Size() function to the mock
Signed-off-by: Yossi Eliaz <yossi@resin.io>

updated the mock of xfer to pass unit test

---

landr.conf.js

**- A picture of a cute animal (not mandatory but encouraged)**

Update website copy

---

vendor.conf
vendor/github.com/docker/libnetwork/portmapper/proxy.go

vendor: update libnetwork to include balena-proxy rename

---

hack/dockerfile/install-binaries.sh
hack/make/.detect-daemon-osarch
hack/make/.integration-daemon-start
integration-cli/check_test.go
integration-cli/daemon/daemon.go
integration-cli/docker_cli_daemon_test.go
integration-cli/docker_cli_events_unix_test.go
restartmanager/restartmanager_test.go

- Balena naming fixing
- Restartmanager unit test fixing

balena additional naming fixes 

---

docs/getting-started.md

Fix Docker capitalisation as reported by @alisondavis17 in [this Flowdock thread](https://www.flowdock.com/app/rulemotion/namechange/threads/yL-BvtrP4eIVxWJsrcPBk7B4iBU).

docs: Fix Docker capitalisation in balenaEngine docs

---

vendor.conf
vendor/github.com/opencontainers/runc/kill.go

vendor: Update runc to include fix for opencontainers/runc#1766

---

libcontainerd/client_daemon.go

[backport] Fix event filter filtering on "or"

---

vendor.conf
vendor/github.com/containerd/cgroups/README.md
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/control.go
vendor/github.com/containerd/cgroups/cpuset.go
vendor/github.com/containerd/cgroups/devices.go
vendor/github.com/containerd/cgroups/net_prio.go
vendor/github.com/containerd/cgroups/opts.go
vendor/github.com/containerd/cgroups/paths.go
vendor/github.com/containerd/cgroups/subsystem.go
vendor/github.com/containerd/cgroups/systemd.go
vendor/github.com/containerd/cgroups/utils.go

Bumps containerd/cgroups@dbea6f2bd41658b84b00417ceefa416b97
Connects-to: https://github.com/docker/for-linux/issues/545

Bump containerd/cgroups

---

daemon/logger/journald/journald.go
daemon/logger/journald/read.go

contains:
- https://github.com/moby/moby/pull/38859
- https://github.com/moby/moby/pull/37819

Backport journald fixes

---

vendor.conf
vendor/github.com/docker/cli/cli/command/image/delta.go

Connects-to: https://github.com/balena-os/balena-engine-cli/pull/9
Connects-to: https://github.com/balena-os/balena-engine/issues/178

Bump CLI dependency to include fix for #178

---

docs/getting-started.md

Closes: #209
Signed-off-by: Miguel Casqueira <miguel@balena.io>

Fixed typos in getting-started.md docs

---

daemon/graphdriver/aufs/aufs.go
daemon/graphdriver/aufs/aufs_test.go
daemon/graphdriver/driver.go
daemon/graphdriver/fsdiff.go
daemon/graphdriver/graphtest/graphtest_unix.go
daemon/graphdriver/overlay2/overlay.go
daemon/graphdriver/overlay2/overlay_test.go
daemon/graphdriver/vfs/driver.go
daemon/graphdriver/vfs/vfs_test.go
layer/filestore.go
layer/filestore_test.go
layer/layer_store.go
layer/layer_store_test.go
layer/migration.go
layer/migration_test.go
layer/ro_layer.go

Cherry-pick of #203 for the master branch.

18.x: Clean up leaked engine data

---

cmd/mobynit/hostapp/mount_container.go
cmd/mobynit/main.go
integration/hostapp/bare_runtime_test.go
integration/hostapp/main_test.go
integration/hostapp/mobynit_test.go
layer/layer_store.go
layer/layer_store_test.go

The previous implementation was not comparing graphdriver content to layerStore mounts.
Signed-off-by: Roman Mazur <roman@balena.io>

Fix container data deletion

---

cmd/mobynit/hostapp/mount_container.go
cmd/mobynit/main.go
daemon/graphdriver/aufs/aufs.go
daemon/graphdriver/aufs/aufs_test.go
daemon/graphdriver/driver.go
daemon/graphdriver/fsdiff.go
daemon/graphdriver/graphtest/graphtest_unix.go
daemon/graphdriver/overlay2/overlay.go
daemon/graphdriver/overlay2/overlay_test.go
daemon/graphdriver/vfs/driver.go
daemon/graphdriver/vfs/vfs_test.go
integration/hostapp/bare_runtime_test.go
integration/hostapp/main_test.go
integration/hostapp/mobynit_test.go
layer/filestore.go
layer/filestore_test.go
layer/layer_store.go
layer/layer_store_test.go
layer/migration.go
layer/migration_test.go
layer/ro_layer.go

Fixes #193
Upstream PR: https://github.com/moby/moby/pull/40795

Clean up leaked engine data

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.versionbot/CHANGELOG.yml
CHANGELOG.md

* codeowners
* issue/pr templates
* s/resin/balena/
* nested changelogs

meta: housekeeping

---

SECURITY.md

Regarding #232 and following https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository

Add a SECURITY.md

---

.github/CODEOWNERS

Drop CODEOWNERS

---

daemon/daemon.go
integration/storagemigration/aufs_to_overlay2_test.go
pkg/storagemigration/aufsutils.go
pkg/storagemigration/commit.go
pkg/storagemigration/failcleanup.go
pkg/storagemigration/migrate.go
pkg/storagemigration/migrate_test.go
pkg/storagemigration/overlayutils.go

storagemigration: fix cleanup condition

---

pkg/storagemigration/migrate.go

reorder the defer statements in the migrate function to only teardown
the logger after the failcleanup function ran. otherwise errors logged
there won't show up in the logfile

storagemigration: capture failcleanup logs in logfile

---

README.md

Add link to post to test landr

---

DEVELOPMENT.md

* Describe the project organization.
* Include a list of commands commonly used during development.
* Update the documentation on how to merge upstream changes, based on my
experience following the instructions for the first time.

Improve docs for balenaEngine devs

---

balena-docs/engine-debugging.md

These are some smaller things I do every now and then when troubleshooting and are worth documenting.

Document a couple of troubleshooting tips

---

.github/actions/publish/action.yml

See: https://github.com/actions/upload-artifact/releases/tag/v4.0.0

Update actions/upload-artifact to v4 and generate unique artifacts
