distribution/pull_v2.go
pkg/ioutils/readers.go

This PR changes the pull behaviour to download and extract at the same time, without first buffering the layer to disk. This reduces the required space for a pull to be exactly the size of the downloaded layers and minimises disk IO.

Streaming pull

---

cmd/mobynit/main.go
daemon/create.go
daemon/create_unix.go
daemon/daemon_unix.go

This PR introduces another type of containers, namely bootable containers, that are meant to be used to bootstrap a system. The distinction is achieved by specifying the `bare` runtime instead of the default `runc`. This disables some actions performed by Docker that interfere with the boot process.
This PR also adds a new command, mobynit, which is meant to be statically compiled and run as PID 1 of a system running bootable containers. This commands contains the absolute minimal code to assemble the root partition of a bootable container, pivot root, and start the normal init process.
The sysroot is mounted at `/mnt/sysroot` of the container mount namespace to allow the bootable container  to update itself.

Bootable containers

---

container/container.go
daemon/graphdriver/aufs/aufs.go
daemon/graphdriver/overlay2/overlay.go
pkg/archive/archive.go
pkg/ioutils/fswriters.go

This repo will become the canonical source for the container engine we ship in resinOS. This PR transfers the existing patches from https://github.com/resin-os/meta-resin/tree/v2.2.0/meta-resin-common/recipes-containers/docker/docker and adapts them to the 17.06 tree.

Meta resin patches

---

cmd/mobynit/main.go
daemon/create_unix.go

There are tree changes here.
First, I switched the root fs layout a bit and made `/current` to be a symlink to a `/hostapps/<container_id>` directory instead of being itself a directory and contain a `container_id` file. The reason for this change is to make changing what the current host app is atomic. A symlink can be atomically renamed to point somewhere else.
Second, any mounts that were performed by an initrd before mobynit had a chance to run will be moved to the new root before pivoting.
Third, reverted shortcircuiting of volume creation for bare containers. Having them there makes things on the host OS update side a bit easier.

Mobynit improvements

---

hack/make/binary-rce-docker
hack/make/dynbinary-rce-docker

Create two flavours of the build, dynamic and static, and also revert stripping the binary. This can be done by downstream users.

Build improvements

---

cmd/mobynit/main.go
vendor.conf

Following the desired resinOS scheme, change the sysroot directory to `/mnt/sysroot/active`, always mount it read/write, and update `golang/x/sys` to include `unix.Fadvise()` support for aarch64

Final tweaks

---

integration-cli/docker_cli_authz_plugin_v2_test.go
integration-cli/docker_cli_daemon_plugins_test.go
integration-cli/docker_cli_events_test.go
integration-cli/docker_cli_inspect_test.go
integration-cli/docker_cli_network_unix_test.go
integration-cli/docker_cli_plugins_logdriver_test.go
integration-cli/docker_cli_plugins_test.go

rce-docker disabled plugin support, therefore we removed its integration tests.
Signed-off-by: Yossi Eliaz <yossi@resin.io>

integration: Skip plugin tests

---

daemon/create.go

Previously the code assumed the source image had at least as many layers
as the destination image.

delta: remove false assumption about src image

---

distribution/push_v1.go

When content addressability was introduced in #17924, a compatibility layer for registry v1 pushes was added. When the engine is asked to push an image to a v1 registry it needs to create v1 IDs for the images.
The strategy so far has been to use the full imageID for the first v1 layer and the ChainID for all other layers, effectively creating as many v1 layers as there are in the image. Only the top most layer contained
the image configuration and the other layers had a dummy json containing only a parent reference.
This becomes problematic when the first layer of the image is big. Consinder the following two Dockerfiles:
```Dockerfile
FROM busybox
RUN create_very_big_file
CMD /foo
```
```Dockerfile
FROM busybox
RUN create_very_big_file
CMD /bar
```
Both of these images will have the …

distribution: separate layer and image config for v1 pushes

---

cmd/mobynit/main.go

Since this is PID 1 it's easier to parameterise it through a file on the
disk rather than having to rely on the bootloader to pass the right
arguments

cmd/mobynit: get graphdriver parameter from disk

---

api/types/types.go
daemon/info.go

This can be used by clients that know how to talk to the extended API balaena provides, e.g creating deltas

daemon: return engine name as part of the version information

---

api/swagger.yaml
daemon/create.go

This addresses two trivial issues found while [browsing](https://github.com/resin-os/balena/pull/35#pullrequestreview-68897068).
- a minor typo in a variable name
- an invalid delta-related URL in swagger.yml

Minor fixes

---

pkg/archive/archive.go

Linux ignores fadvise for dirty pages so we need to make sure we sync to
have them marked as clean before discarding
Ref: https://github.com/torvalds/linux/blob/v4.13/mm/truncate.c#L489-L493

pkg/archive: sync files before issuing the fadvise syscall

---

.github/ISSUE_TEMPLATE.md

balena inherited the issue template from Docker; it should customize it. This patch notes the issue and fixes part of it.

Issue template should refer to balena throughout

---

container/container.go
daemon/health.go
daemon/monitor.go
restartmanager/restartmanager.go

Start treating an unhealthy container as a failure condition. Restarts are only initiated if a restart policy is set.

daemon: experimental: restart container when they become unhealthy

---

container/container.go
daemon/monitor.go

We can't just convert struct pointer that is `nil` to an anonymous field
type. Anonymous fields behave in the same way like fields and will
segfault if accessed without checking.

healthcheck: fix docker segfaulting

---

daemon/rename.go

defers are called in the opposite way that they were declared. The container is already being locked in the function

container: remove extraneous lock leading to deadlocks

---

vendor.conf
vendor/github.com/containerd/btrfs/README.md
vendor/github.com/containerd/btrfs/btrfs.go
vendor/github.com/containerd/btrfs/doc.go
vendor/github.com/containerd/btrfs/helpers.go
vendor/github.com/containerd/btrfs/info.go

When building with BTRFS enabled, currently running into an issue:
```
---> Making bundle: binary-balena (in bundles/binary-balena)
Building: bundles/binary-balena/balena-dev
.gopath/src/github.com/docker/docker/vendor/github.com/containerd/btrfs/btrfs.go:103: constant 18446744073709551616 overflows _Ctype_ulonglong
.gopath/src/github.com/docker/docker/vendor/github.com/containerd/btrfs/btrfs.go:104: constant 18446744073709551616 overflows _Ctype_ulonglong
.gopath/src/github.com/docker/docker/vendor/github.com/containerd/btrfs/btrfs.go:105: constant 18446744073709551616 overflows _Ctype_ulonglong
```
Upstream seems to have fixed this very issue in https://github.com/containerd/containerd/pull/2190 and that same vendoring is done in the PR.
Run build with this PR, …

vendor: update btrfs dependency

---

pkg/stringid/stringid.go

Seeding the math/random RNG with a crypto grade seed slows down startup
on embedded devices that don't have enough entropy during early boot.
Furthermore math/rand is seeded by a lot of other packages with
non-crypto grade seeds which makes it a last write wins situation.
Since math/rand is only used in the GenerateNonCryptoID function, we
make it always use the current time as a seed to avoid startup delays.
Signed-off-by: Petros Angelatos <petrosagg@gmail.com>
**- A picture of a cute animal (not mandatory but encouraged)**

pkg/stringid: don't bother seeding math/random with crypto grade seed

---

pkg/ioutils/eagerwriter.go

EagerFileWriter will schedule immediate writeback of dirty pages. The
writes will only block if the device's write queue is full, which
provides throttling without incuring the latency cost of fsync.

pkg/ioutils: implement eager writer

---

build.sh
hack/make.sh

Updated the build scripts to correctly set the CLI and server version information
Setting the right environment variables and build time flags for the go compiler, to match the requirements of the build script.
Before this PR the version check results are:
```
$ ./balena -v     
balena version unknown-version, build unknown-commit
$ ./balena version
Client:
Version:	unknown-version
API version:	1.35
Go version:	go1.10.3
Git commit:	unknown-commit
Built:	unknown-buildtime
OS/Arch:	linux/amd64
Experimental:	false
Orchestrator:	swarm
Server:
Engine:
Version:	dev
API version:	1.35 (minimum version 1.12)
Go version:	go1.10.3
Git commit:	2fe3ad156
Built:	Tue Aug 28 12:10:00 2018
OS/Arch:	linux/amd64
Experimental:	false
```
Build the PR, …

version: fix version strings reported in the cli

---

cmd/mobynit/main.go

Added a few patches to add support for mounting rootfs from a custom path
By copying existing code in mobynit and modifying it.
I tested it on a raspberry pi3 running resinOS
```
root@resin:/tmp# ./mobynit -layer-root /mnt/sysroot/inactive/
/mnt/sysroot/inactive/balena/aufs/mnt/572e07e5a91cbb6d43593c5cc56d20a7b0d9438ca9841645932cad5a94e3280broot@resin:/tmp# 
root@resin:/tmp# ls /mnt/sysroot/inactive/balena/aufs/mnt/572e07e5a91cbb6d43593c5cc56d20a7b0d9438ca9841645932cad5a94e3280b    
bin   dev  home  linuxrc  mnt   quirks      resin-data           run   srv  tmp  var
boot  etc  lib   media    proc  resin-boot  resinos.fingerprint  sbin  sys  usr
root@resin:/tmp# 
```
mobynit: Add support for …

mobynit: Add support for mounting rootfs from a custom path

---

Dockerfile
integration-cli/docker_cli_build_test.go
integration-cli/docker_cli_by_digest_test.go
integration-cli/docker_cli_create_test.go
integration-cli/docker_cli_daemon_test.go
integration-cli/docker_cli_events_unix_test.go
integration-cli/docker_cli_exec_test.go
integration-cli/docker_cli_external_volume_driver_unix_test.go
integration-cli/docker_cli_info_test.go
integration-cli/docker_cli_logout_test.go
integration-cli/docker_cli_network_unix_test.go
integration-cli/docker_cli_oom_killed_test.go
integration-cli/docker_cli_proxy_test.go
integration-cli/docker_cli_prune_unix_test.go
integration-cli/docker_cli_pull_test.go
integration-cli/docker_cli_pull_trusted_test.go
integration-cli/docker_cli_push_test.go
integration-cli/docker_cli_registry_user_agent_test.go
integration-cli/docker_cli_run_test.go
integration-cli/docker_cli_run_unix_test.go
integration-cli/docker_cli_userns_test.go
integration-cli/docker_cli_v2_only_test.go
integration-cli/docker_hub_pull_suite_test.go
integration/container/restart_test.go

Before this pull request, running `go` integration tests as per Dockerfile instructions (`hack/make.sh test-integration`) would result in ~1270 passed tests and ~180 failed tests. The failures appear to be caused by docker features that are intentionally not implemented by balenaEngine, but further detailed investigation is required. Skipping those tests for now allows one to verify their code changes against tests that are known to pass, thus providing us an immediate benefit.

Skip integration tests that are pending balenaEngine compatibility investigation

---

vendor.conf
vendor/github.com/containerd/containerd/plugin/plugin_go18.go

Note: the result of running the `vndr` tool did not result in additional changes under this pull request because most of the renaming changes had already been merged when incorrectly "manually" updating the contents of the vendor folder (not using the `vndr` tool) in a previous renaming pull request.

Run vndr tool for balena-cli and balena-libnetwork (balenaEngine rename)

---

api/server/router/image/backend.go
api/server/router/image/image_routes.go
api/types/client.go
client/image_delta.go
client/interface.go
daemon/create.go
integration/image/delta_test.go

Similar to how the build command allows tagging of images this allows
specifying a repo:tag indentifier to tag the delta with
Change-type: minor

Allow tagging of image deltas on creation

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c

Tested on Raspberry Pi 3 with balenaOS 2.29.2+rev2
<details>
```
+ balena-engine --version
balena-engine version 17.12.0-dev, build dceb2fc48071b78a8a828e0468a15a479515385f
+ balena info
+ grep -i 'Default Runtime'
Default Runtime: runc
+ balena ps
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                   PORTS               NAMES
c2117e3059d3        cve-mem-test_work                  "/usr/bin/entry.sh /…"   About an hour ago   Up 5 seconds                                 cve-mem-test_work_1
caa1f5b3e988        balena/armv7hf-supervisor:v9.0.1   "./entry.sh"             4 hours ago         Up 8 minutes (healthy)                       resin_supervisor
+ systemd-cgtop -n1
+ head -n 5
/ …
```

vendor: Update runc to include fix for CVE-2019-5736

---

.travis.yml

Since we build in docker anyway we can save the time it usually takes to
set up the Go environment.
See: https://docs.travis-ci.com/user/languages/minimal-and-generic/

travis: use minimal image and stages

---

daemon/graphdriver/aufs/aufs.go
daemon/graphdriver/overlay2/overlay.go
integration/image/pull_test.go

This patch adds a driver option to enalble/disable the to disk syncing introduced in
684d8ba.
The default is still to sync all currently mounted filesystems before
reporting an ApplyDiff as successful.
Connects-to: #133

Allow to turn off fs syncing on every layer diff for aufs/overlay2 storage drivers

---

cmd/dockerd/config.go
daemon/config/config.go
daemon/daemon.go
daemon/images/service.go
daemon/reload.go
distribution/xfer/download.go
distribution/xfer/download_test.go
distribution/xfer/upload.go
distribution/xfer/upload_test.go
plugin/backend_linux.go

The defaults remain the same (dl=5, ul=5), but are moved from distribution/xfer to
daemon/config.
Connects-to: https://github.com/balena-os/balena-engine/issues/160

Add daemon flags to configure max download/upload attempts during pull/push

---

Dockerfile.build.aarch64
Dockerfile.build.arm
Dockerfile.build.i386
Dockerfile.build.x86_64

and remove outdated "libsystemd-journal-dev" package
This should fix the recent build failures on the 17.12-resin branch

[17.12] dockerfile-build: move to balenalib

---

api/types/container/host_config.go
daemon/create.go
integration/container/cid_env_test.go
vendor.conf
vendor/github.com/docker/cli/cli/command/container/opts.go

This adds a new ContainerIDEnv field to HostConfig that can pass an
environment variable name, which will be set to the container ID and
passed to the container environment.
Connects-to: https://github.com/balena-os/balena-engine/issues/173

Allow passing container ID to container via environment variable

---

build.sh

We don't support these on balenaOS anyway and we are planning to drop
support once we move to the new balenaCI-based pipeline.

build.sh: Disable btrfs,zfs,devicemapper graphdrivers

---

contrib/beind/Dockerfile
contrib/beind/README.md
contrib/beind/balena-entrypoint.sh
contrib/beind/balenad-entrypoint.sh
contrib/beind/modprobe.sh

This modifies https://github.com/docker-library/docker for balena-engine
Used for the integration tests of a2o-migrate #168, but I thought it might be useful outside of that...

contrib: Add balena-engine version of dind container

---

pkg/authorization/authz_unix_test.go
pkg/authorization/middleware_unix_test.go

On macOS, unit tests where failing with
```
root@c4101a75c792:/go/src/github.com/docker/docker/pkg/authorization# go test .
--- FAIL: TestAuthZRequestPluginError (0.00s)
authz_unix_test.go:295: listen unix authz-test-plugin.sock: bind: file name too long
--- FAIL: TestAuthZRequestPlugin (0.00s)
authz_unix_test.go:295: listen unix authz-test-plugin.sock: bind: file name too long
--- FAIL: TestAuthZResponsePlugin (0.00s)
authz_unix_test.go:295: listen unix authz-test-plugin.sock: bind: file name too long
time="2020-04-07T10:07:04Z" level=warning msg="Request body is larger than: '1048576' skipping body"
--- FAIL: TestMiddlewareWrapHandler (0.00s)
authz_unix_test.go:295: listen unix authz-test-plugin.sock: bind: file name too long
FAIL
FAIL	github.com/docker/docker/pkg/authorization	0.120s …
```

pkg/authorization: Fix test failures on macOS

---

daemon/graphdriver/btrfs/btrfs.go
daemon/graphdriver/btrfs/btrfs_test.go
daemon/graphdriver/btrfs/dummy_unsupported.go
daemon/graphdriver/btrfs/version.go
daemon/graphdriver/btrfs/version_test.go
hack/dockerfile/install/gotestsum.installer
hack/make.sh
profiles/seccomp/seccomp.go
profiles/seccomp/seccomp_test.go

balena-os/balena-engine-cli@20c1983
moves the versioning variables to a separate package. We have to adjust
the location in hack/make.sh too
also backports a fix from upstream to fix the gotestsum installer

Fix CLI versioning

---

daemon/top_unix.go

Busybox in balenaOS is compiled with desktop mode disabled,
so features like `-ef` and providing pids via `-q` are not
supported. Add a 3rd condition to try ps with no args and allow
parsePSOutput to filter by pid.
https://github.com/balena-os/balena-engine/issues/236
Signed-off-by: Kyle Harding <kyle@balena.io>
Adjusted `balena top` to not pass any args to `ps` for cases where a minimal busybox, not procps, is used.
There were already two conditions to try passing different args into ps, including one that didn't provide `-qpid1,pid2` so we are already relying on the pid filter in `parsePSOutput`. I added a 3rd fallback to also avoid passing `-ef`.
I built a custom balenaOS image for raspberrypi4-64 and …

top_unix.go: allow busybox ps with no args

---

pkg/storagemigration/migrate.go
pkg/storagemigration/migrate_test.go

verify with `make TESTDIRS=./pkg/storagemigration test-unit`, prior to b8170db554ac1d1abb3adcfe1f6265701e9147c5 should panic like this:
```
=== FAIL: pkg/storagemigration TestMigrateFailure (0.01s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x92f3c8]
goroutine 12 [running]:
testing.tRunner.func1(0xc0000ceb00)
/usr/local/go/src/testing/testing.go:830 +0x392
panic(0x9be440, 0x1109f70)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/docker/docker/pkg/storagemigration.Migrate(0xc00009d320, 0x21, 0xb175a0, 0xc000065c40)
/go/src/github.com/docker/docker/pkg/storagemigration/migrate.go:54 +0x2a8 …
```

pkg/storagemigration: poperly handle errors during state creation

---

daemon/images/image_delta.go
integration/image/delta_test.go

During fingerpinting of the source image the destination layers are not
exepmt from being released (e.g. when `balena image rm <iid>`) is run
simultaneously.
Similarly when processing the destination layers to generate deltas we
only hold one reference at a time, leaving the subsequent layers
vulnerable to the same issues.

Lock destination layers while delta is being processed

---

distribution/pull_v2.go

This commit changes the way we retry layer downloads after failures with
the goal of making it more resilient, especially for cases involving
large layers and unreliable network connections.
These are the changes:
* Make sure we also retry after failures in `v2LayerDescriptor.reset()`.
This method creates a new HTTP request to resume a failed download,
and therefore depends on a working network to succeed.
* Wait exponentially longer times between retries (instead of retrying
immediately as before). This shall increase of success in case of
network issues that take longer to get resolved.
* Increase the number of retries to 10.
* Reset retry count whenever we successfully download anything at all.
The idea is that we want to give up downloading only after a long
continuous period of …

Make layer download resuming more resilient

---

pkg/ioutils/concat.go

prevent slice oob access in concatReadSeekCloser

---

pkg/storagemigration/migrate.go
pkg/storagemigration/utils.go

instead of our own implementation

pkg/storagemigration: use graphdriver/copy.DirCopy

---

distribution/pull_v2.go

We currently do not log any information to help us understanding the
underlying issue -- not even to identify what is the exact point in
which the error is raised. This commit improves on this situation.
Meant to help with #244.

Log more info when raising errRootFSMismatch

---

distribution/pull_v2.go

This adds some context to the error message when there's some error
loading the delta base image (for example, when the delta base image is
not found locally).
The error message we had before was generic and low-level, which didn't
give any clues about what lead to the error.
Signed-off-by: Leandro Motta Barros <leandro@balena.io>

Improve error reporting for delta base image loading

---

Dockerfile
vendor.conf
vendor/github.com/vishvananda/netlink/addr_linux.go

balenaEngine initialization would fail on devices connected to the
network via PPP (Point-to-Point Protocol) and with a nil destination
address (0.0.0.0):
panic: runtime error: invalid memory address or nil pointer dereference
This commit updates the netlink dependency to a fork where we
cherry-picked the correction. This correction wasn't available in any
stable release of netlink, so we opted to use this fork instead of
relying on a beta netlink version. We can obsolete our fork once Moby
starts using a netlink version that includes the fix.

Fix crash with PPP interface with nil dst address

---

.github/actions/publish/action.yml

The existing cross target does not disable netgo or osusergo so instead we will use QEMU to build dynbinary for other platforms.
Signed-off-by: Kyle Harding <kyle@balena.io>
As expected, cross-building with emulation (QEMU) is much slower than with the Golang toolchains, but it produces the dynamic binaries we need without modifying the upstream Moby build scripts.

Cross-build the dynbinary target

---

DEVELOPMENT.md
daemon/images/image_pull.go
integration/image/delta_test.go

We apparently have broken this during the 20.10 merge. Not setting the delta image store breaks delta-based balenaOS updates (HUPs).
(Bonus: tossed in a few commits refactoring the delta test cases a bit for simplicity and clarity.)
Fixes #318
Testing:
* Tested manually: on a Pi 3 running a recent (not latest) balenaOS, ran a HUP e checked in the logs that the delta-based HUP failed. Compiled a version of the Engine from my branch, replaced the Engine on the device, tried another HUP: logs no longer showed an error for the delta-based HUP.
* Added an integration test case that pulls a delta whose basis image is present only in the directory specified as the delta image root. This test case failed before the changes, and passes after them.
* Considered adding a test case to balenaOS …

Set the delta image store, fix delta-based HUPs

---

balena-docs/engine-debugging.md

Hello folks, I bring docs.
These docs were part of the debugging masterclass.
I am trying to make debugging masterclasses render dynamically from the content present in main docs as much as they can.
This lead to me transferring docs to their rightful places.
Plan is to have these docs live in the balenaEngine repo, and then main docs pulling these in to generate the masterclass.
What I need help in:
1. Product owners giving these docs a once over to update outdated information or
2. Straight up, merge this PR.
I am transferring these docs straight from the debugging masterclass so please leave the headings how they currently are. Anything else can be modified.
Please commit directly to make the changes on this PR. I don't have the bandwidth to resolve issues with the docs themselves. …

patch: Migrate balenaEngine Debugging docs from masterclass

---

.github/actions/publish/action.yml
hack/make.sh

This reverts commit 0240d94e35a43be595cd5e79b0653440c228229f.
Those needing cgo for netdns should build dynbinary from source with cgo support.
https://pkg.go.dev/net#hdr-Name_Resolution

Revert "Cross-build the dynbinary target"

---

vendor.conf
vendor/github.com/docker/libnetwork/endpoint.go
vendor/github.com/docker/libnetwork/sandbox_store.go

This updates balena-libnetwork to a version that should fix some port binding issues that may happen after balenaEngine or device crashes. Specifically, this balena-libnetwork version cherry-picks [this unmerged upstream patch](https://github.com/moby/libnetwork/pull/1805) (with minor changes to make it compatible with recent Moby versions).
I cannot comment on the precise details, but this patch essentially changes the order of initialization of some network-related components in order to avoid getting into a inconsistent state.
Fixes #272 (at least shall fix *some* of its occurrences)
**Testing**
Tested for regressions: Engine unit tests and integration tests passing. Tried it in a [meta-balena branch](https://github.com/balena-os/meta-balena/pull/3108); all tests passed. Also did some …

Update libnetwork to fix port binding issue

---

distribution/pull_v2.go

Previously, we'd time-out a pull operation after unsuccessfully retrying for about 17 minutes (for details see commit
582487f832c59c2f734a780ab0492833f29002c9). This worked fine in most situations, but we have seen at least one case of a particularly unreliable network connection that would not be able to finish a large pull when operating under this policy.
This commit:
* Completely removes timeouts from image pulls. We'll keep retrying forever, or until users cancel the pull. (From the perspective of the REST API, "canceling" mean closing the HTTP connection. This is what happens when a user Ctrl+C during a pull in the CLI, or, say, we kill a curl process that was using the REST API to pull image.)
* Still uses exponential back-off, but we now limit the interval between retries to 5 …

Further improve resilience of image pulls

---

integration/image/delta_test.go
pkg/ioutils/concat.go
pkg/ioutils/concat_test.go

Previously, `concatReadSeekCloser.Read()` would incorrectly return
an `io.ErrUnexpectedEOF` if the last read from the second concatenated
`Reader` didn't completely fill the passed buffer.
For instance:
```
First Reader    Second Reader
|aaaaaaaaaaaaa|bbbbbbbbbbbbbbbbbbb|      <--- concatReadSeekCloser
|--- previously read ---|--- buffer ---| <--- last read
|xxxx| <--- "excess" buffer
```
In this example, we have a `concatReadSeekCloser` that concatenates two
`Reader`s (`aaa...` and `bbb...`). The last `Read()` used a buffer
larger than the yet-to-be-read portion of the `bbb...`. So, it would
incorrectly return an `io.ErrUnexpectedEOF`.
This commit makes sure that last `Read()` returns all the remaining data
without an error. It also adds various test cases for …

Bugfix: concatReadSeekCloser.Read() with buffers of any size

---

DEVELOPMENT.md
vendor.conf
vendor/github.com/containerd/containerd/pkg/apparmor/apparmor.go
vendor/github.com/containerd/containerd/pkg/apparmor/apparmor_linux.go

This updates balena-containerd to a new version in which we cherry-picked the change from here: https://github.com/containerd/containerd/pull/8086
This change avoids enabling AppArmor if the `/sbin/apparmor_parser` binary is not found in the system.

Don't enable AppArmor if `apparmor_parser` is not present

---

DEVELOPMENT.md

Simple update to development doc 'Build and run' instructions. It's not necessary to explicitly start `balena-engine-containerd`; this is done automatically by `balena-engine-daemon`.
Review `DEVELOPMENT.md`.
Simplify development doc 'Build and run' instructions

Simplify development doc 'Build and run' instructions

---

distribution/pull_v2.go
image/tarexport/load.go

This fixes a bug introduced in the refactoring made during the work on [Delta on load](https://github.com/balena-os/balena-engine/pull/374). The previous implementation was closing the base image stream before it was even used.
This effectively marked layers as no longer locked, which means other concurrent tasks would be able to remove them while they were still needed. So, this PR is very likely to help with #444 -- possibly solving it entirely (though it's hard to test or otherwise confirm this with 100% certainty).
The solution implemented here is simple enough: we make it clear who is responsible for closing this stream, and ensure it is closed only after it's used.

Bugfix: Don't close base images prematurely
